{% set name = "serializable" %}
{% set version = "0.4.0" %}
{% set sha256 = "28987f54a381a994f59870a2010d083ab5e872f579cc09ca4a1fa562da32026d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - pypandoc
  run:
    - python >=3.6
    - typechecks >=0.0.2
    - six >=1.9.0
    - simplejson

test:
  imports:
    - serializable

about:
  home: https://github.com/iskandr/serializable
  license: Apache-2.0
  summary: 'Base class with serialization helpers for user-defined Python objects'
  license_family: Apache
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'

extra:
  recipe-maintainers:
    - npavlovikj
