travis:
  secure:
    BINSTAR_TOKEN: XB9x89Dx7xqFG2NGk/nKRb34u3upIIGuTinrkM4u8QBF7kJAs/3KEU2ZgxdG9hJ0VEbhIPTLVdjjMSwoXtQ9PiL+EHVAm3fdk03FMSWLZJJFtkuVfQY5o0KpXyqVad7ZEmxQ6b9yXcssCMjExtvUttxkH00/+VbdX28kI1GcDc70PVhSLBRBUWNqvjBBEMA3nBJmU/oxA+hvnsUiXC+hRYqiYReylzqe+VdEpg8CO5uXOnj7o0lvE0NWSk6JhUB1xQkvXv8ve1BgObvZW+ga6HRnb5VKGE4CU+Zk2h76IIJtnpKS9qPB6/Pj4A+E87qTrN+XdYHgL1jivfmStTBHdPVlInz7Qly2GXKq4Mzdl7al67ubjaDnxKb62EV8crtQ5K2cQeUSAUEYrLXN9vgOqPMOydVq9M9PTKA5uiDb90hYz26K25LKfwy/qO846XeMClJaUsNxDlfPNSHBApklGr3uhAmPO9I5qtIkMC6wVMhFKewIy+7u6zP6Hg5Uh/GBBMEPCui/lWPZGasJnU7FX4QlTG1F8ls3czxVLW7GCKpBcGw17YxLXwgsVlYHrt9MYD5WBsnDB/JBmOHyChq/O3kqwWFcjHTPeFWdbGUsjAtW1IO3XEo1O7/5CBxubLNblMwYAJ6oG9IzWHTHl7YNGiPiTsU9y7AF9infYZ/J8Hk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
