travis:
  secure:
    BINSTAR_TOKEN: d6e9Zef60f5MAV8O1U6anKJEkevy46A2tNqkgnXbyewXzvoGKfE9t6NySl9Fgru7GN5glIk0MndlykEAFVAxkK19t7jC/+zyoUH6o4DX5VjixPRKHXqD4JMY6QZ+i+cVQfIUwNYH+N9UMj2NKBE/JwiscE3lfxIefWNCo3xC7N4haHNC6InbfVBSB03v2oEtP6BwSd5J09gi9PGyHgHhuulCil5XmZ9/0iJWS2djKTqecjU5Nl+IgzWik+/ppZVfidM9z53QP+EmBYKRoB/KFDfJk4WsL0ByrBnQu4wiY8goF2tv6+8JJbKeFIOvFawRJwxROs/YNXHmkFvtzyNewSetGUQ9hwYLmH1B6xKG5SsWgQQZalHs0K0NolMInOWiNoShgGCT/tCIV0h7qwrzbDH5ccNWY4TPUjWVV/CzOUMga2HWmC8H2Tk+tFa3rOjYb1IK42T1z2VJ0FmiBiyOz6IwDHWOOtNm1G2vYY+QpAFI0WbDnH0BPCt0Ke/DNRIX8PGtgHq6dqYGA7gGcZ5e3pUtInwNTi2T9yNwEZivWC7GT4fCYRWZU5cYPVMmuddIS1RBKYsiU6cDf9MHaROw73iInFLy0h9rTWa2WkA17GXqdMe8prqCfx1ubo34cge3LJvYpHzVAAgvZyHLmMkDp6HtVLb7rX9wGhnRUpVEwqA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
